name: Build and Push to Docker Hub

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
    paths-ignore:
      - 'mcp/**'
      - 'mcp/.*'
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - 'mcp/**'
      - 'mcp/.*'
      - '**.md'
      - 'docs/**'

env:
  IMAGE_NAME: plantuml-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/org/apache/maven
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: lihongjie0209/${{ env.IMAGE_NAME }}
        tags: |
          # Version tags (highest priority)
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          # Branch-based tags
          type=ref,event=branch
          # PR tags
          type=ref,event=pr
          # Latest tag only for main branch and version tags
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
          # SHA-based tags for traceability
          type=sha,prefix={{branch}}-,enable={{is_default_branch}}
        flavor: |
          # Disable automatic latest tag generation
          latest=false
          
    - name: Show Docker tags that will be generated
      run: |
        echo "Docker tags that will be generated:"
        echo "${{ steps.meta.outputs.tags }}"
        echo ""
        echo "Docker labels:"
        echo "${{ steps.meta.outputs.labels }}"
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: |
          type=gha
          type=registry,ref=lihongjie0209/${{ env.IMAGE_NAME }}:buildcache
        cache-to: |
          type=gha,mode=max
          type=registry,ref=lihongjie0209/${{ env.IMAGE_NAME }}:buildcache,mode=max
        platforms: linux/amd64,linux/arm64
        
    - name: Update Docker Hub description
      if: github.event_name != 'pull_request'
      continue-on-error: true
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: lihongjie0209/plantuml-server
        readme-filepath: ./README.md
